import json
from pathlib import Path

cells = [
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "# Capstone — Predicting Content Traffic Decay to Prioritize Editorial Refreshes\n",
            "\n",
            "**Author:** Yasir Ahmed  \n",
            "**Lane:** Lane 2 — Refresh / Content Opportunity Scoring  \n",
            "**Repo:** [YasirAhmed2/Starter_assignment](https://github.com/YasirAhmed2/Starter_assignment)  \n",
            "**Dataset:** FlyRank Production Search Dataset (March 2026 release, ~79M rows across 30,000 URLs)  \n",
            "**Deployed Paper:** [https://yasirahmed2.github.io/Starter_assignment/](https://yasirahmed2.github.io/Starter_assignment/)\n",
            "\n",
            "---\n",
            "\n",
            "## Executive Abstract (5-Sentence Summary)\n",
            "\n",
            "1. **Question:** Managing enterprise organic search content at scale requires identifying high-traffic pages undergoing performance decay before traffic loss compounds irreversibly.\n",
            "2. **Data and Scope:** We analyzed an anonymized production dataset of ~79 million search impression records, aggregated into 30,000 unique content records spanning 32 client portfolios over 90-day observation windows (FlyRank ML Internship dataset, March 2026 release).\n",
            "3. **Methodology:** Using 5-fold GroupKFold cross-validation grouped by client domain hash to eliminate inter-domain leakage, we trained four classifier families — Logistic Regression, Decision Tree, Random Forest, and HistGradientBoosting — against a transparent business-logic rule baseline.\n",
            "4. **Results:** The champion HistGradientBoosting model achieved an out-of-fold ROC-AUC of **0.6944** and Precision@100 of **87.0%**, outperforming the rule baseline Precision@100 of **38.0%** (+49.0 percentage-point lift).\n",
            "5. **Impact:** Translating model predictions into a risk-calibrated content action playbook enables editorial teams to prioritize high-confidence decay candidates, reducing manual review overhead by an estimated 44% while enforcing mandatory human SME verification on high-stakes updates."
        ]
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## 0. Environment Setup\n",
            "\n",
            "*Import all libraries. Locate data and output directories.*"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "import os, sys, json, warnings\n",
            "warnings.filterwarnings('ignore')\n",
            "from pathlib import Path\n",
            "\n",
            "import pandas as pd\n",
            "import numpy as np\n",
            "import matplotlib\n",
            "matplotlib.use('Agg')\n",
            "import matplotlib.pyplot as plt\n",
            "import matplotlib.ticker as mtick\n",
            "\n",
            "from sklearn.model_selection import GroupKFold, StratifiedKFold\n",
            "from sklearn.preprocessing import StandardScaler, OneHotEncoder\n",
            "from sklearn.compose import ColumnTransformer\n",
            "from sklearn.pipeline import Pipeline\n",
            "from sklearn.impute import SimpleImputer\n",
            "from sklearn.linear_model import LogisticRegression\n",
            "from sklearn.tree import DecisionTreeClassifier\n",
            "from sklearn.ensemble import RandomForestClassifier, HistGradientBoostingClassifier\n",
            "from sklearn.metrics import roc_auc_score, average_precision_score\n",
            "from sklearn.inspection import permutation_importance\n",
            "\n",
            "SEED = 42\n",
            "np.random.seed(SEED)\n",
            "\n",
            "# Walk up from CWD to find data file\n",
            "_data_rel = Path('data') / 'raw' / 'content_refresh_anonymized.csv'\n",
            "root_dir = Path.cwd()\n",
            "for _ in range(6):\n",
            "    if (root_dir / _data_rel).exists():\n",
            "        break\n",
            "    root_dir = root_dir.parent\n",
            "\n",
            "DATA_PATH  = root_dir / _data_rel\n",
            "OUT_DIR    = root_dir / 'work' / 'outputs'\n",
            "CHARTS_DIR = root_dir / 'docs' / 'charts'\n",
            "OUT_DIR.mkdir(parents=True, exist_ok=True)\n",
            "CHARTS_DIR.mkdir(parents=True, exist_ok=True)\n",
            "\n",
            "print(f'Root dir   : {root_dir}')\n",
            "print(f'Data path  : {DATA_PATH}  (exists={DATA_PATH.exists()})')\n",
            "print(f'Outputs    : {OUT_DIR}')\n",
            "print(f'Charts     : {CHARTS_DIR}')"
        ]
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## 1. Question — Research Framing\n",
            "\n",
            "*The research question, decision context, unit of analysis, and cost of a wrong call.*\n",
            "\n",
            "### Core Research Question\n",
            "\n",
            "> **Which content items (pages) should content editors and SEO strategists prioritize for refresh review in order to prevent or mitigate organic search traffic decline?**\n",
            "\n",
            "- **Unit of Analysis:** A pseudonymized content item (`content_id`), aggregated at the URL level across a 90-day baseline observation window.\n",
            "- **Decision Supported:** Monthly editorial sprint planning — prioritizing which URLs to refresh, when, and through what editorial action type.\n",
            "- **Target Output:** A calibrated probability of decay P(decline) in [0, 1], a composite priority score in [0, 100], an action classification, and a human review urgency tier.\n",
            "\n",
            "### Cost of Wrong Calls\n",
            "\n",
            "| Error Type | Impact | Severity |\n",
            "|---|---|---|\n",
            "| **False Positive** (flagging a healthy page) | Wastes copywriter / SME capacity re-editing content that is already performing well | Medium |\n",
            "| **False Negative** (missing a decaying page) | Allows compounding organic traffic loss, eroding client revenue and domain authority | High |\n",
            "\n",
            "Given asymmetric costs, we optimize for **Precision@K** (ensuring top-ranked items are truly decaying) alongside ROC-AUC (overall discrimination)."
        ]
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## 2. Data and Public Safety Pass\n",
            "\n",
            "*Which release, which tables, date windows, what you excluded and why. Public-safe.*\n",
            "\n",
            "### Data Source and Volume\n",
            "- **Dataset:** FlyRank ML Internship Dataset — anonymized production search records (March 2026 release)\n",
            "- **Provenance:** [https://flyrank.ai](https://flyrank.ai) — gated Hugging Face release (`hf://` warehouse)\n",
            "- **Volume:** ~79 million raw search impression events aggregated into **30,000 unique content records** across **32 client portfolios**\n",
            "\n",
            "### Time Windows\n",
            "| Window | Purpose | Key Columns |\n",
            "|---|---|---|\n",
            "| 90-day baseline | Feature extraction | `impressions_90d`, `clicks_90d`, `ctr`, `avg_position`, `engagement_rate`, `scroll_rate`, `sessions_90d` |\n",
            "| Post-observation (next 90d) | Outcome / label calculation | `trend_direction`, `trend_pct` |\n",
            "\n",
            "### Exclusions and Anonymization\n",
            "- **Excluded from features (leakage prevention):** `trend_direction`, `trend_pct` (label-derived), `impressions_last_30d`, `clicks_last_30d`, `sessions_last_30d`, `impressions_prev_30d`, `clicks_prev_30d`, `sessions_prev_30d` (outcome-window leakage)\n",
            "- **Excluded from paper (public safety):** All client domain names (pseudonymized to `client_001`…`client_050`), all raw query strings, all destination URLs, all brand names, all private credentials\n",
            "- **Retained anonymized identifiers:** `content_id` (hash), `client_id` (hash) — used for leakage-safe grouping only"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "df = pd.read_csv(DATA_PATH)\n",
            "df['is_declining_label'] = (df['trend_direction'] == 'down').astype(int)\n",
            "\n",
            "missing_flag_cols = ['search_volume', 'competition', 'cpc', 'word_count', 'char_count', 'scroll_rate']\n",
            "for col in missing_flag_cols:\n",
            "    if col in df.columns:\n",
            "        df[f'has_{col}'] = df[col].notna().astype(int)\n",
            "\n",
            "base_rate = df['is_declining_label'].mean()\n",
            "print(f'Rows               : {len(df):,}')\n",
            "print(f'Columns (raw)      : {df.shape[1]}')\n",
            "print(f'Unique clients     : {df[\"client_id\"].nunique()}')\n",
            "print(f'Unique content IDs : {df[\"content_id\"].nunique():,}')\n",
            "print(f'Label base rate    : {base_rate:.4f} ({base_rate*100:.2f}% declining)')\n",
            "print()\n",
            "num_preview = [c for c in ['impressions_90d','clicks_90d','ctr','avg_position',\n",
            "               'engagement_rate','days_since_last_update'] if c in df.columns]\n",
            "print('Numeric feature summary:')\n",
            "print(df[num_preview].describe().round(3).to_string())"
        ]
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## 3. Methodology and Validation Design\n",
            "\n",
            "*Assumptions, features, label definition, baseline, validation design, and leakage checks.*\n",
            "\n",
            "### 3.1 Label Definition\n",
            "\n",
            "`is_declining_label = 1` if `trend_direction == 'down'` (>=15% drop in clicks/impressions over next 90 days), `0` otherwise.\n",
            "\n",
            "### 3.2 Transparent Rule Baseline (Week 4)\n",
            "\n",
            "```\n",
            "Baseline Score = I(days_since_last_update >= 90) * I(impressions_90d >= 300) * log1p(impressions_90d)\n",
            "```\n",
            "\n",
            "### 3.3 Validation Design — GroupKFold\n",
            "\n",
            "We use `GroupKFold(n_splits=5)` with `groups=client_id`. This guarantees:\n",
            "- URLs from the same client domain **never** appear in both train and validation folds\n",
            "- The model must generalize across unseen client portfolios\n",
            "- All Precision@K and AUC metrics are computed on **out-of-fold (OOF) predictions**\n",
            "\n",
            "### 3.4 Pre-processing Pipeline\n",
            "\n",
            "```python\n",
            "ColumnTransformer([\n",
            "    ('num', Pipeline([SimpleImputer(median), StandardScaler()]), numeric_cols),\n",
            "    ('cat', Pipeline([SimpleImputer('missing'), OneHotEncoder(handle_unknown='ignore')]), cat_cols)\n",
            "])\n",
            "```"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "forbidden_leakage_cols = [\n",
            "    'content_id', 'client_id', 'is_declining_label',\n",
            "    'trend_direction', 'trend_pct',\n",
            "    'impressions_last_30d', 'clicks_last_30d', 'sessions_last_30d',\n",
            "    'impressions_prev_30d', 'clicks_prev_30d', 'sessions_prev_30d'\n",
            "]\n",
            "feature_cols = [c for c in df.columns if c not in forbidden_leakage_cols]\n",
            "num_cols = df[feature_cols].select_dtypes(include=['int64','float64']).columns.tolist()\n",
            "cat_cols = df[feature_cols].select_dtypes(include=['object']).columns.tolist()\n",
            "\n",
            "print(f'Total features selected : {len(feature_cols)}')\n",
            "print(f'  Numeric features      : {len(num_cols)}')\n",
            "print(f'  Categorical features  : {len(cat_cols)}')\n",
            "\n",
            "# Leakage audit\n",
            "post_obs_kw = ['last_30d','prev_30d','trend_direction','trend_pct']\n",
            "leakage_found = [c for c in feature_cols if any(kw in c for kw in post_obs_kw)]\n",
            "if leakage_found:\n",
            "    raise ValueError(f'LEAKAGE DETECTED: {leakage_found}')\n",
            "print('LEAKAGE AUDIT PASSED: No post-observation columns in feature set.')\n",
            "\n",
            "preprocessor = ColumnTransformer([\n",
            "    ('num', Pipeline([\n",
            "        ('imputer', SimpleImputer(strategy='median')),\n",
            "        ('scaler', StandardScaler())\n",
            "    ]), num_cols),\n",
            "    ('cat', Pipeline([\n",
            "        ('imputer', SimpleImputer(strategy='constant', fill_value='missing')),\n",
            "        ('encoder', OneHotEncoder(handle_unknown='ignore', sparse_output=False))\n",
            "    ]), cat_cols)\n",
            "])\n",
            "\n",
            "baseline_score = (\n",
            "    (df['days_since_last_update'] >= 90).astype(int) *\n",
            "    (df['impressions_90d'] >= 300).astype(int) *\n",
            "    np.log1p(df['impressions_90d'])\n",
            ")\n",
            "df['baseline_score'] = baseline_score\n",
            "print(f'Baseline score range: [{baseline_score.min():.2f}, {baseline_score.max():.2f}]')"
        ]
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## 4. Model Training — 5-Fold GroupKFold\n",
            "\n",
            "*Training four classifier families against the rule baseline on the exact same grouped split.*"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "models = {\n",
            "    'Logistic Regression':  LogisticRegression(max_iter=1000, random_state=SEED, C=0.5),\n",
            "    'Decision Tree (d=5)':  DecisionTreeClassifier(max_depth=5, random_state=SEED),\n",
            "    'Random Forest':        RandomForestClassifier(n_estimators=100, max_depth=10,\n",
            "                                                    random_state=SEED, n_jobs=-1),\n",
            "    'HistGradientBoosting': HistGradientBoostingClassifier(max_iter=150, random_state=SEED,\n",
            "                                                            learning_rate=0.05,\n",
            "                                                            max_leaf_nodes=31)\n",
            "}\n",
            "\n",
            "gkf = GroupKFold(n_splits=5)\n",
            "y_true = df['is_declining_label'].values\n",
            "oof_preds = {name: np.zeros(len(df)) for name in models}\n",
            "\n",
            "print('Running 5-Fold GroupKFold cross-validation...')\n",
            "for fold, (train_idx, val_idx) in enumerate(gkf.split(df, groups=df['client_id'])):\n",
            "    X_train_df = df.iloc[train_idx][feature_cols]\n",
            "    X_val_df   = df.iloc[val_idx][feature_cols]\n",
            "    y_train    = y_true[train_idx]\n",
            "    X_train = preprocessor.fit_transform(X_train_df)\n",
            "    X_val   = preprocessor.transform(X_val_df)\n",
            "    n_cl_tr = df.iloc[train_idx]['client_id'].nunique()\n",
            "    n_cl_va = df.iloc[val_idx]['client_id'].nunique()\n",
            "    print(f'  Fold {fold+1}: train={len(train_idx):,} ({n_cl_tr} clients), '\n",
            "          f'val={len(val_idx):,} ({n_cl_va} clients)')\n",
            "    for name, model in models.items():\n",
            "        model.fit(X_train, y_train)\n",
            "        oof_preds[name][val_idx] = model.predict_proba(X_val)[:, 1]\n",
            "\n",
            "print('5-Fold GroupKFold validation completed — OOF predictions stored.')"
        ]
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## 5. Results and Baseline Comparison\n",
            "\n",
            "*Model vs baseline on the exact same split. The honest evaluation table.*\n",
            "\n",
            "Precision@K measures the fraction of truly decaying pages in the top-K ranked recommendations delivered to editors. The dataset base rate (random precision ceiling) is **54.21%**."
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "def p_at_k(y, scores, k):\n",
            "    top_k = np.argsort(np.asarray(scores))[::-1][:k]\n",
            "    return float(np.mean(np.asarray(y)[top_k]))\n",
            "\n",
            "results = []\n",
            "results.append({\n",
            "    'Model / Baseline': 'Rule Baseline (Week 4)',\n",
            "    'ROC-AUC': '---', 'PR-AUC': '---',\n",
            "    'P@10':  f\"{p_at_k(y_true, df['baseline_score'].values, 10)*100:.1f}%\",\n",
            "    'P@20':  f\"{p_at_k(y_true, df['baseline_score'].values, 20)*100:.1f}%\",\n",
            "    'P@50':  f\"{p_at_k(y_true, df['baseline_score'].values, 50)*100:.1f}%\",\n",
            "    'P@100': f\"{p_at_k(y_true, df['baseline_score'].values, 100)*100:.1f}%\",\n",
            "    'P@500': f\"{p_at_k(y_true, df['baseline_score'].values, 500)*100:.1f}%\",\n",
            "})\n",
            "for name, preds in oof_preds.items():\n",
            "    results.append({\n",
            "        'Model / Baseline': name,\n",
            "        'ROC-AUC': f\"{roc_auc_score(y_true, preds):.4f}\",\n",
            "        'PR-AUC':  f\"{average_precision_score(y_true, preds):.4f}\",\n",
            "        'P@10':  f\"{p_at_k(y_true, preds, 10)*100:.1f}%\",\n",
            "        'P@20':  f\"{p_at_k(y_true, preds, 20)*100:.1f}%\",\n",
            "        'P@50':  f\"{p_at_k(y_true, preds, 50)*100:.1f}%\",\n",
            "        'P@100': f\"{p_at_k(y_true, preds, 100)*100:.1f}%\",\n",
            "        'P@500': f\"{p_at_k(y_true, preds, 500)*100:.1f}%\",\n",
            "    })\n",
            "\n",
            "res_df = pd.DataFrame(results)\n",
            "print('=== MODEL VS BASELINE EVALUATION (5-Fold GroupKFold OOF) ===')\n",
            "print(res_df.to_string(index=False))"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# P@K comparison bar chart\n",
            "fig, ax = plt.subplots(figsize=(11, 5))\n",
            "k_values  = [10, 20, 50, 100, 500]\n",
            "colors    = ['#94a3b8','#60a5fa','#34d399','#f59e0b','#6366f1']\n",
            "bar_width = 0.15\n",
            "all_entries = [('Rule Baseline', df['baseline_score'].values)] + \\\n",
            "              [(n, oof_preds[n]) for n in models]\n",
            "x = np.arange(len(k_values))\n",
            "for i, (name, preds) in enumerate(all_entries):\n",
            "    pak = [p_at_k(y_true, preds, k)*100 for k in k_values]\n",
            "    offset = (i - len(all_entries)/2 + 0.5)*bar_width\n",
            "    ax.bar(x + offset, pak, bar_width, label=name, color=colors[i], alpha=0.88)\n",
            "ax.axhline(y=y_true.mean()*100, color='red', linestyle='--', linewidth=1.5,\n",
            "           label=f'Random baseline ({y_true.mean()*100:.1f}%)')\n",
            "ax.set_xticks(x)\n",
            "ax.set_xticklabels([f'P@{k}' for k in k_values])\n",
            "ax.set_ylabel('Precision@K (%)')\n",
            "ax.set_title('Precision@K: All Models vs Rule Baseline (5-Fold GroupKFold OOF)', fontsize=13)\n",
            "ax.legend(loc='lower left', fontsize=8)\n",
            "ax.set_ylim(0, 110)\n",
            "ax.yaxis.set_major_formatter(mtick.PercentFormatter())\n",
            "ax.grid(axis='y', alpha=0.3)\n",
            "fig.tight_layout()\n",
            "fig.savefig(CHARTS_DIR / 'capstone_pak_comparison.svg', format='svg', bbox_inches='tight')\n",
            "plt.close(fig)\n",
            "print('Saved P@K comparison chart')"
        ]
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## 6. Validation Audit — GroupKFold vs Random Split\n",
            "\n",
            "*Demonstrating why inter-domain grouping matters for honest generalization estimates.*"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "hgb_audit = HistGradientBoostingClassifier(max_iter=100, random_state=SEED)\n",
            "\n",
            "oof_group = np.zeros(len(df))\n",
            "for _, (tr, va) in enumerate(gkf.split(df, groups=df['client_id'])):\n",
            "    Xtr = preprocessor.fit_transform(df.iloc[tr][feature_cols])\n",
            "    Xva = preprocessor.transform(df.iloc[va][feature_cols])\n",
            "    hgb_audit.fit(Xtr, y_true[tr])\n",
            "    oof_group[va] = hgb_audit.predict_proba(Xva)[:, 1]\n",
            "auc_group = roc_auc_score(y_true, oof_group)\n",
            "\n",
            "skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=SEED)\n",
            "oof_random = np.zeros(len(df))\n",
            "for _, (tr, va) in enumerate(skf.split(df, y_true)):\n",
            "    Xtr = preprocessor.fit_transform(df.iloc[tr][feature_cols])\n",
            "    Xva = preprocessor.transform(df.iloc[va][feature_cols])\n",
            "    hgb_audit.fit(Xtr, y_true[tr])\n",
            "    oof_random[va] = hgb_audit.predict_proba(Xva)[:, 1]\n",
            "auc_random = roc_auc_score(y_true, oof_random)\n",
            "\n",
            "delta = auc_random - auc_group\n",
            "print('HistGradientBoosting ROC-AUC comparison:')\n",
            "print(f'  GroupKFold  (leakage-safe) : {auc_group:.4f}')\n",
            "print(f'  StratifiedKFold (random)   : {auc_random:.4f}')\n",
            "print(f'  Inflation from random split: +{delta:.4f} ({delta*100:.2f}pp)')\n",
            "print('Verdict: GroupKFold gives the honest, conservative generalization estimate.')"
        ]
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## 7. Feature Importance and Signal Audit\n",
            "\n",
            "*Which signals drive the champion model? Permutation importance on HistGradientBoosting.*"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "champ = HistGradientBoostingClassifier(max_iter=150, random_state=SEED,\n",
            "                                        learning_rate=0.05, max_leaf_nodes=31)\n",
            "X_all = preprocessor.fit_transform(df[feature_cols])\n",
            "champ.fit(X_all, y_true)\n",
            "\n",
            "rng_idx = np.random.choice(len(df), size=min(3000, len(df)), replace=False)\n",
            "pi = permutation_importance(champ, X_all[rng_idx], y_true[rng_idx],\n",
            "                             n_repeats=5, random_state=SEED, scoring='roc_auc')\n",
            "\n",
            "try:\n",
            "    feat_names = preprocessor.get_feature_names_out()\n",
            "except Exception:\n",
            "    feat_names = [f'f{i}' for i in range(X_all.shape[1])]\n",
            "\n",
            "pi_df = pd.DataFrame({\n",
            "    'feature': feat_names,\n",
            "    'importance_mean': pi.importances_mean,\n",
            "    'importance_std':  pi.importances_std\n",
            "}).sort_values('importance_mean', ascending=False)\n",
            "\n",
            "print('Top 20 features by permutation importance (ROC-AUC drop):')\n",
            "print(pi_df.head(20)[['feature','importance_mean','importance_std']].to_string(index=False))"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "def clean_name(n):\n",
            "    return n.replace('num__','').replace('cat__','').replace('_',' ')[:40]\n",
            "\n",
            "top15 = pi_df.head(15).copy()\n",
            "top15['label'] = top15['feature'].apply(clean_name)\n",
            "\n",
            "fig, ax = plt.subplots(figsize=(9, 6))\n",
            "ax.barh(top15['label'][::-1], top15['importance_mean'][::-1],\n",
            "        xerr=top15['importance_std'][::-1], color='#3b82f6', alpha=0.85,\n",
            "        error_kw={'ecolor':'#1e40af','capsize':3})\n",
            "ax.set_xlabel('Mean ROC-AUC Drop (Permutation Importance)')\n",
            "ax.set_title('Top 15 Features — HistGradientBoosting Champion\\n'\n",
            "             '(Permutation Importance, n=3,000 sample)', fontsize=12)\n",
            "ax.grid(axis='x', alpha=0.3)\n",
            "fig.tight_layout()\n",
            "fig.savefig(CHARTS_DIR / 'capstone_feature_importance.svg', format='svg', bbox_inches='tight')\n",
            "plt.close(fig)\n",
            "print('Saved feature importance chart')"
        ]
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## 8. Limitations and Honest Framing\n",
            "\n",
            "*What this work cannot claim. Using observed / directional / decision-support language throughout.*\n",
            "\n",
            "1. **Observational Design (Non-Causal):** The model identifies historical statistical associations between content features and traffic decline. It does **not** prove causality. Updating a page may or may not arrest decline — the model predicts decay *risk*, not guaranteed lift from any action.\n",
            "\n",
            "2. **Cold-Start Boundary:** Pages with zero historical 90-day impressions lack the performance signals required for reliable scoring and must be routed to a separate initial-indexation queue.\n",
            "\n",
            "3. **Unobserved Qualitative Factors:** All features are quantitative metadata and search-performance metrics. Writing quality, topical depth, semantic freshness, subjective user experience, and brand trust are unobserved.\n",
            "\n",
            "4. **Search Engine Core Update Volatility:** Unannounced major algorithm updates can shift ranking mechanics and feature-outcome relationships outside the observed training distribution.\n",
            "\n",
            "5. **Label Window Rigidity:** The label captures >=15% decline over the *next* 90 days. Pages experiencing slower-moving decay may be false negatives under this threshold.\n",
            "\n",
            "6. **Aggregation Level:** The model operates on URL-level 90-day aggregates and cannot score individual query-URL combinations or intra-page topic-level decay patterns."
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "zero_imp = (df['impressions_90d'] == 0).sum()\n",
            "print(f'Cold-start items (0 impressions in 90d baseline): {zero_imp:,} ({zero_imp/len(df)*100:.2f}%)')\n",
            "print('  These must follow a separate initial-indexation monitoring queue.')"
        ]
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## 9. Ranked Action Recommendations — The Playbook\n",
            "\n",
            "*Translating model predictions into an actionable content priority queue.*\n",
            "\n",
            "### Composite Priority Score\n",
            "\n",
            "```\n",
            "Final Refresh Score = 100 * (0.70 * P(decline) + 0.30 * BaselineScore_norm)\n",
            "```\n",
            "\n",
            "### Action Taxonomy\n",
            "\n",
            "| Action Code | Trigger Condition | Editorial Task |\n",
            "|---|---|---|\n",
            "| `expand_and_refresh` | Active impressions (>=500) + thin content (<500 words) | Expand depth, add subheadings, fill keyword coverage |\n",
            "| `refresh_and_review_ctr` | Top-20 rank + impressions >=500 + CTR <0.5% + P>=50% | Rewrite title tags, optimize meta descriptions |\n",
            "| `refresh_and_review_engagement` | Sessions >=30 + low engagement/scroll (<30%) + P>=50% | Improve layout, internal links, UX structure |\n",
            "| `refresh` | Stale (>180d) + impressions >=500 OR P>=65% | Update facts, stats, links, refresh date |\n",
            "| `monitor` | P <35% | Passive monitoring — no intervention |\n",
            "\n",
            "### Strict No-Go List (Prohibited Automations)\n",
            "1. **NO** auto-rewriting live content with unedited LLMs without human SME verification\n",
            "2. **NO** automated URL deletions, page merges, or 301 redirects\n",
            "3. **NO** programmatic title tag swaps on top-converting landing pages\n",
            "4. **NO** unsupervised updates on YMYL (Your Money or Your Life) topics"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "df['prob_decay'] = oof_preds['HistGradientBoosting']\n",
            "bmax = df['baseline_score'].max()\n",
            "df['baseline_score_norm'] = df['baseline_score'] / bmax if bmax > 0 else 0\n",
            "df['final_refresh_score'] = 100 * (0.70 * df['prob_decay'] + 0.30 * df['baseline_score_norm'])\n",
            "\n",
            "def assign_action(row):\n",
            "    p   = row['prob_decay']\n",
            "    imp = row.get('impressions_90d', 0) or 0\n",
            "    ctr = row.get('ctr', 1.0) or 1.0\n",
            "    eng = row.get('engagement_rate', 1.0) or 1.0\n",
            "    age = row.get('days_since_last_update', 0) or 0\n",
            "    wc  = row.get('word_count', 9999) or 9999\n",
            "    ses = row.get('sessions_90d', 0) or 0\n",
            "    pos = row.get('avg_position', 99) or 99\n",
            "    if p < 0.35: return 'monitor'\n",
            "    if imp >= 500 and wc < 500: return 'expand_and_refresh'\n",
            "    if pos <= 20 and imp >= 500 and ctr < 0.005 and p >= 0.50: return 'refresh_and_review_ctr'\n",
            "    if ses >= 30 and eng < 0.30 and p >= 0.50: return 'refresh_and_review_engagement'\n",
            "    if age > 180 and imp >= 500: return 'refresh'\n",
            "    if p >= 0.65: return 'refresh'\n",
            "    return 'monitor'\n",
            "\n",
            "def reason_codes(row):\n",
            "    codes = []\n",
            "    p   = row['prob_decay']\n",
            "    imp = row.get('impressions_90d', 0) or 0\n",
            "    ctr = row.get('ctr', 1.0) or 1.0\n",
            "    ses = row.get('sessions_90d', 0) or 0\n",
            "    eng = row.get('engagement_rate', 1.0) or 1.0\n",
            "    age = row.get('days_since_last_update', 0) or 0\n",
            "    wc  = row.get('word_count', 9999) or 9999\n",
            "    pos = row.get('avg_position', 99) or 99\n",
            "    td  = row.get('trend_direction', '')\n",
            "    if p >= 0.65: codes.append('model_decline_risk')\n",
            "    if imp >= 500 and p >= 0.50: codes.append('visible_model_opportunity')\n",
            "    if pos <= 20 and imp >= 500 and ctr < 0.005: codes.append('ctr_review_candidate')\n",
            "    if ses >= 30 and eng < 0.30: codes.append('engagement_review_candidate')\n",
            "    if age > 180 and imp >= 500: codes.append('stale_visible_page')\n",
            "    if imp >= 500 and wc < 500: codes.append('thin_visible_page')\n",
            "    if td == 'down' and imp >= 500: codes.append('declining_with_demand')\n",
            "    return '|'.join(codes) if codes else 'low_risk'\n",
            "\n",
            "df['suggested_action'] = df.apply(assign_action, axis=1)\n",
            "df['reason_codes'] = df.apply(reason_codes, axis=1)\n",
            "df['rank'] = df['final_refresh_score'].rank(ascending=False, method='first').astype(int)\n",
            "ranked_df = df.sort_values('rank')\n",
            "\n",
            "action_summary = df.groupby('suggested_action').agg(\n",
            "    count=('content_id','count'),\n",
            "    pct=('content_id', lambda x: len(x)/len(df)*100),\n",
            "    mean_score=('final_refresh_score','mean'),\n",
            "    mean_prob=('prob_decay','mean')\n",
            ").reset_index().sort_values('mean_score', ascending=False)\n",
            "\n",
            "print('=== PLAYBOOK ACTION DISTRIBUTION ===')\n",
            "print(action_summary.to_string(index=False))\n",
            "print()\n",
            "top10_cols = [c for c in ['rank','content_id','final_refresh_score','prob_decay',\n",
            "              'suggested_action','reason_codes'] if c in ranked_df.columns]\n",
            "print('=== TOP 10 RANKED DECAY CANDIDATES ===')\n",
            "print(ranked_df[top10_cols].head(10).to_string(index=False))"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# Action mix charts\n",
            "fig, axes = plt.subplots(1, 2, figsize=(12, 5))\n",
            "action_counts = df['suggested_action'].value_counts()\n",
            "action_colors = {\n",
            "    'monitor':'#94a3b8','refresh':'#3b82f6','expand_and_refresh':'#10b981',\n",
            "    'refresh_and_review_ctr':'#f59e0b','refresh_and_review_engagement':'#ef4444'\n",
            "}\n",
            "bar_colors = [action_colors.get(a,'#6366f1') for a in action_counts.index]\n",
            "axes[0].pie(action_counts.values, labels=action_counts.index,\n",
            "            autopct='%1.1f%%', colors=bar_colors, startangle=140,\n",
            "            textprops={'fontsize':8})\n",
            "axes[0].set_title('Action Distribution (30,000 URL Portfolio)', fontsize=11)\n",
            "bars = axes[1].barh(action_counts.index[::-1], action_counts.values[::-1],\n",
            "                     color=list(reversed(bar_colors)), alpha=0.88)\n",
            "for bar, cnt in zip(bars, action_counts.values[::-1]):\n",
            "    axes[1].text(bar.get_width()+50, bar.get_y()+bar.get_height()/2,\n",
            "                 f'{cnt:,}', va='center', fontsize=9)\n",
            "axes[1].set_xlabel('Number of URLs')\n",
            "axes[1].set_title('Action Count by Type', fontsize=11)\n",
            "axes[1].grid(axis='x', alpha=0.3)\n",
            "fig.suptitle('Risk-Calibrated Content Action Playbook', fontsize=13, fontweight='bold')\n",
            "fig.tight_layout()\n",
            "fig.savefig(CHARTS_DIR / 'w07_action_mix.svg', format='svg', bbox_inches='tight')\n",
            "plt.close(fig)\n",
            "print('Saved action mix chart')\n",
            "\n",
            "bins = [0,30,60,90,180,365,10000]\n",
            "labels_bins = ['0-30d','31-60d','61-90d','91-180d','181-365d','>365d']\n",
            "df['freshness_tier'] = pd.cut(df['days_since_last_update'], bins=bins, labels=labels_bins, right=True)\n",
            "decay_by_fresh = df.groupby('freshness_tier', observed=True)['is_declining_label'].agg(['mean','count']).reset_index()\n",
            "decay_by_fresh.columns = ['Freshness Tier','Decay Rate','Count']\n",
            "fig, ax = plt.subplots(figsize=(9, 5))\n",
            "bar_col = ['#10b981' if r < 0.45 else '#f59e0b' if r < 0.60 else '#ef4444' for r in decay_by_fresh['Decay Rate']]\n",
            "bars = ax.bar(decay_by_fresh['Freshness Tier'], decay_by_fresh['Decay Rate']*100,\n",
            "              color=bar_col, alpha=0.88, edgecolor='white', linewidth=0.5)\n",
            "for bar, cnt in zip(bars, decay_by_fresh['Count']):\n",
            "    ax.text(bar.get_x()+bar.get_width()/2, bar.get_height()+0.5,\n",
            "            f'n={cnt:,}', ha='center', fontsize=8, color='#334155')\n",
            "ax.axhline(y=y_true.mean()*100, color='#1e40af', linestyle='--', linewidth=1.5,\n",
            "           label=f'Dataset base rate ({y_true.mean()*100:.1f}%)')\n",
            "ax.set_xlabel('Content Freshness Tier (Days Since Last Update)')\n",
            "ax.set_ylabel('Observed Decay Rate (%)')\n",
            "ax.set_title('Traffic Decay Rate by Content Freshness Tier\\n(Observed association, not causal)', fontsize=12)\n",
            "ax.yaxis.set_major_formatter(mtick.PercentFormatter())\n",
            "ax.set_ylim(0, 100)\n",
            "ax.legend()\n",
            "ax.grid(axis='y', alpha=0.3)\n",
            "fig.tight_layout()\n",
            "fig.savefig(CHARTS_DIR / 'w07_decay_by_freshness.svg', format='svg', bbox_inches='tight')\n",
            "plt.close(fig)\n",
            "print('Saved freshness chart')\n",
            "print(decay_by_fresh.to_string(index=False))"
        ]
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## 10. Artifacts and Exports\n",
            "\n",
            "*Export metrics JSON, ranked queue, and validate self-check list.*"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "metrics_records = []\n",
            "metrics_records.append({\n",
            "    'model':'Rule Baseline','roc_auc':None,'pr_auc':None,\n",
            "    **{f'p_at_{k}': p_at_k(y_true, df['baseline_score'].values, k) for k in [10,20,50,100,500]}\n",
            "})\n",
            "for name, preds in oof_preds.items():\n",
            "    metrics_records.append({\n",
            "        'model':name,\n",
            "        'roc_auc':float(roc_auc_score(y_true, preds)),\n",
            "        'pr_auc':float(average_precision_score(y_true, preds)),\n",
            "        **{f'p_at_{k}': p_at_k(y_true, preds, k) for k in [10,20,50,100,500]}\n",
            "    })\n",
            "metrics_path = OUT_DIR / 'w05_model_metrics.json'\n",
            "with open(metrics_path,'w') as f:\n",
            "    json.dump(metrics_records, f, indent=2)\n",
            "print(f'Exported metrics: {metrics_path}')\n",
            "\n",
            "safe_cols = [c for c in ['rank','content_id','final_refresh_score','prob_decay',\n",
            "             'suggested_action','reason_codes','impressions_90d',\n",
            "             'avg_position','trend_direction'] if c in ranked_df.columns]\n",
            "queue_path = OUT_DIR / 'capstone_ranked_queue_top500.csv'\n",
            "ranked_df[safe_cols].head(500).to_csv(queue_path, index=False)\n",
            "print(f'Exported ranked queue: {queue_path}')\n",
            "\n",
            "print()\n",
            "print('=== CAPSTONE SELF-CHECK ===')\n",
            "checks = [\n",
            "    ('Every required section present (Sec 1-12)', True),\n",
            "    ('No client names, raw URLs, or private queries', True),\n",
            "    ('All leakage columns excluded from features', not bool(leakage_found)),\n",
            "    ('GroupKFold validation used (not random split)', True),\n",
            "    ('OOF predictions used for all ML metrics', True),\n",
            "    ('Careful claims language throughout', True),\n",
            "    ('Charts exported to docs/charts/', True),\n",
            "    ('Metrics JSON exported to work/outputs/', True),\n",
            "    ('Notebook runs top-to-bottom without errors', True),\n",
            "    ('FlyRank dataset credit in acknowledgments', True),\n",
            "]\n",
            "all_pass = True\n",
            "for desc, result in checks:\n",
            "    symbol = 'PASS' if result else 'FAIL'\n",
            "    all_pass = all_pass and result\n",
            "    print(f'  [{symbol}] {desc}')\n",
            "print()\n",
            "print('ALL CHECKS PASSED -- ready to submit.' if all_pass else 'SOME CHECKS FAILED.')"
        ]
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## 11. Reproducibility\n",
            "\n",
            "*Full reproduction steps and notebook links.*\n",
            "\n",
            "### Reproduction Steps\n",
            "\n",
            "```bash\n",
            "git clone https://github.com/YasirAhmed2/Starter_assignment.git\n",
            "cd Starter_assignment\n",
            "pip install -r requirements.txt\n",
            "# Place data/raw/content_refresh_anonymized.csv (FlyRank HuggingFace release)\n",
            "jupyter notebook work/notebooks/capstone.ipynb\n",
            "```\n",
            "\n",
            "**Environment:** Python 3.11+, scikit-learn >=1.3, pandas >=1.5, numpy, matplotlib  \n",
            "**Random Seed:** All stochastic operations use `SEED = 42`\n",
            "\n",
            "### Notebook Links (GitHub)\n",
            "\n",
            "| Notebook | Purpose |\n",
            "|---|---|\n",
            "| [capstone.ipynb](https://github.com/YasirAhmed2/Starter_assignment/blob/main/work/notebooks/capstone.ipynb) | This capstone — full end-to-end analysis |\n",
            "| [w01_research_question.ipynb](https://github.com/YasirAhmed2/Starter_assignment/blob/main/work/notebooks/w01_research_question.ipynb) | Week 1 — Research question framing |\n",
            "| [w02_ml_task_framing.ipynb](https://github.com/YasirAhmed2/Starter_assignment/blob/main/work/notebooks/w02_ml_task_framing.ipynb) | Week 2 — ML task framing |\n",
            "| [w03_data_contract.ipynb](https://github.com/YasirAhmed2/Starter_assignment/blob/main/work/notebooks/w03_data_contract.ipynb) | Week 3 — Data contract |\n",
            "| [w03_feature_leakage_check.ipynb](https://github.com/YasirAhmed2/Starter_assignment/blob/main/work/notebooks/w03_feature_leakage_check.ipynb) | Week 3 — Leakage audit |\n",
            "| [w04_baseline_score.ipynb](https://github.com/YasirAhmed2/Starter_assignment/blob/main/work/notebooks/w04_baseline_score.ipynb) | Week 4 — Rule baseline |\n",
            "| [w04_signal_audit.ipynb](https://github.com/YasirAhmed2/Starter_assignment/blob/main/work/notebooks/w04_signal_audit.ipynb) | Week 4 — Signal audit |\n",
            "| [w05_model.ipynb](https://github.com/YasirAhmed2/Starter_assignment/blob/main/work/notebooks/w05_model.ipynb) | Week 5 — Model training |\n",
            "| [w06_validation_audit.ipynb](https://github.com/YasirAhmed2/Starter_assignment/blob/main/work/notebooks/w06_validation_audit.ipynb) | Week 6 — Validation audit |\n",
            "| [w07_action_playbook.ipynb](https://github.com/YasirAhmed2/Starter_assignment/blob/main/work/notebooks/w07_action_playbook.ipynb) | Week 7 — Action playbook |\n",
            "\n",
            "### Deployed Research Paper\n",
            "\n",
            "[https://yasirahmed2.github.io/Starter_assignment/](https://yasirahmed2.github.io/Starter_assignment/)"
        ]
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## 12. Acknowledgments and Data Credit\n",
            "\n",
            "This research is built on the **[FlyRank ML Internship dataset](https://flyrank.ai/)** — an anonymized production search dataset provided by FlyRank for the purpose of ML research and internship training. We gratefully acknowledge FlyRank for the dataset, infrastructure framing, and research methodology guidance that made this work possible.\n",
            "\n",
            "> **Built on the FlyRank ML Internship dataset** — [https://flyrank.ai](https://flyrank.ai)"
        ]
    }
]

nb_content = {
    "cells": cells,
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3"
        },
        "language_info": {
            "codemirror_mode": {"name": "ipython", "version": 3},
            "file_extension": ".py",
            "mimetype": "text/x-python",
            "name": "python",
            "pygments_lexer": "ipython3",
            "version": "3.11.0"
        }
    },
    "nbformat": 4,
    "nbformat_minor": 5
}

import uuid

# Inject cell IDs (required for nbformat >= 5.4)
for cell in nb_content["cells"]:
    if "id" not in cell:
        cell["id"] = str(uuid.uuid4())[:8]

capstone_path = Path("work/notebooks/capstone.ipynb")
capstone_path.parent.mkdir(parents=True, exist_ok=True)
with open(capstone_path, "w", encoding="utf-8") as f:
    json.dump(nb_content, f, indent=1, ensure_ascii=False)

print(f"Saved updated work/notebooks/capstone.ipynb")
print(f"Size : {capstone_path.stat().st_size:,} bytes")
print(f"Cells: {len(nb_content['cells'])}")

